//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryabiWindows
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KaryabiDBEntities : DbContext
    {
        public KaryabiDBEntities()
            : base("name=KaryabiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CatWork> tbl_CatWork { get; set; }
        public virtual DbSet<tbl_Customers> tbl_Customers { get; set; }
        public virtual DbSet<tbl_JobCategory> tbl_JobCategory { get; set; }
        public virtual DbSet<tbl_Manager> tbl_Manager { get; set; }
        public virtual DbSet<tbl_Officers> tbl_Officers { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_Notify> tbl_Notify { get; set; }
        public virtual DbSet<tbl_NotifyFromAdmin> tbl_NotifyFromAdmin { get; set; }
    }
}
