//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryabiWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Birth { get; set; }
        public string CodeMelli { get; set; }
        public string Tell { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string WorkName { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> FlagAdmin { get; set; }
        public string OfficerValid { get; set; }
    }
}
