//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryabiWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CatWork
    {
        public string Id { get; set; }
        public string WorkName { get; set; }
    }
}
