//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryabiWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Officers
    {
        public string OfficerId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Birth { get; set; }
        public string TheWork { get; set; }
        public string CodeMelli { get; set; }
        public string Tell { get; set; }
        public string Mobile { get; set; }
        public string DateInCompany { get; set; }
        public string Madrak { get; set; }
        public byte[] Image { get; set; }
        public string Address { get; set; }
    }
}
